spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interconnect
    username: root
    password: Lapsangsouchong1!

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true